apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-apps
  template:
    metadata:
      labels:
        app: my-apps
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: praqma/network-multitool
